### ISSUE TITLE
Problem with New Package (wrong paths in type.d.ts)

### ISSUE THREAD

**Issue by jogibear9988** [adobe/css-tools#116]
in the new package the paths in type.d.ts are wrong

see:
![image](https://user-images.githubusercontent.com/364896/227019607-bdc20404-5b82-43e6-8d75-627effc0281d.png)

**Comment by holblin** [comment]
Is the problem with the current version or the `4.3.0-beta.2`?
I was planning to release version `4.3.0` soon (I didn't get the time to do it earlier) and if you could confirm if there is some work on it or if that solves this issue that would be amazing!

Thanks,

**Comment by jogibear9988** [comment]
beta.2
you could see the wrong paths on npm

**Comment by amandaghassaei** [comment]
confirming this issue is on 4.3.0-beta.2 - rolling back to v4.2.0 fixed the problem for me.

**Comment by jogibear9988** [comment]
@holblin any news to the broken beta.2 package?

**Comment by holblin** [comment]
I will take some time this week or next week to make a new beta package that tries to solve the issues of beta.2 without introducing a regression. That get out of my todo list somehow. Sorry for that.

**Comment by holblin** [comment]
How is the `4.3.0-rc.1` @jogibear9988 and @amandaghassaei ? Does that fix your problems?
If so I'll release the `4.3.0`.

**Comment by amandaghassaei** [comment]
That has fixed all my issues, thanks for the update!

**Comment by jogibear9988** [comment]
yes, works now
