### ISSUE TITLE
Requiring this package as a dependency fails

### ISSUE THREAD

**Issue by crs1138** [adobe/css-tools#182]
### Expected Behaviour

```js
var cssTools = require('@adobe/css-tools');
```

This should let me use `cssTools.parse()`.

### Actual Behaviour

When trying to use matchers from @testing-library/jest-dom I get the following error message:  
`Cannot find module '@adobe/css-tools' from 'node_modules/@testing-library/jest-dom/dist/matchers-d012a0f1.js'`

**Comment by hsavit1** [comment]
getting the same error

**Comment by holblin** [comment]
Hi,

Could you confirm which exact version of the package is installed?
I believe it might not be the latest version (which fixes some very similar issues).

Best regards,

**Comment by hsavit1** [comment]
@holblin this got fixed for me today with the 6.1.2 update of the jest-marchers

**Comment by holblin** [comment]
Perfect and thanks for the info! I understand the issue a little bit better now 👍
I'll wait a day or two for @crs1138 confirmation and will close if he confirms or if there are no new messages :-)

For reference: https://github.com/testing-library/jest-dom/pull/525

**Comment by crs1138** [comment]
Hi there. Thank you for following this up. I can confirm that the v6.1.2 of @testing-library/jest-dom - works correctly. You can dismiss my PR.
