### ISSUE TITLE
@import does not work if url contains ';'

### ISSUE THREAD

**Issue by steffanhalv** [adobe/css-tools#71]
### Expected Behaviour
This should be parsed correctly
```js
let demo = cssCompiler.parse(`
@import url('https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@300;400;500;700;900&display=swap');
.test {
  background: red;
  font-family: 'Zen Kaku Gothic New', sans-serif;
}
`)

console.log('demo', demo)
```

### Actual Behaviour

`@import url('https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@300``

Becomes the first declaration and `400;500;700;900&display=swap')`the second.

#### Steps to Reproduce

Run the code above

#### Platform and Version

4.0.1

#### Sample Code that illustrates the problem

Look ahead

#### Logs taken while reproducing problem

N/A

**Comment by holblin** [comment]
Hi @steffanhalv , could you check if this PR fixes your problems?
- https://github.com/adobe/css-tools/pull/88
I plan to merge it within a week if I found no issues with it.

**Comment by holblin** [comment]
The new version is published in npm 👍 
Thanks for the report! It was much appreciated :-)
