### ISSUE TITLE
Regression in selector parsing: Attribute selectors not parsed correctly

### ISSUE THREAD

**Issue by RandomByte** [adobe/css-tools#77]
Thank you for this fork of `css`. It's very helpful to us.

While testing, I think I have found a regression in the parser, introduced with commit https://github.com/adobe/css-tools/commit/24ed6e753fee6f0874446953ed75ae35806ab98c:

https://github.com/adobe/css-tools/blob/a0efaee362ef472ab00c9b2e2786289808081ae3/src/parse/index.ts#L215-L239

The regular expression `/("|')(?:\\\1|.)*?,(?:\\\1|.)*?\1|\(.*?,.*?\)/g` seems to be too greedy for cases like `div[class='foo'],div[class='bar']`. For this example, it captures `'foo'],div[class='`, leading to an incorrect replacement of the comma that separates the two selectors and is not part of the data selector.

The original regular expression, used before this change ([`/"(?:\\"|[^"])*"|'(?:\\'|[^'])*'/g`](https://github.com/adobe/css-tools/blob/434aa1733f275a67ea700311451b98a14f8cc21a/lib/parse/index.js#L202)) handles this case correctly by matching `'foo'` and `'bar'`.

Ultimately, the current behavior leads to an incorrect AST, where instead of two selectors, only one (incorrect) selector is listed:
```json
"type": "rule",
"selectors": [
    "div[data-value='foo'],div[data-value='bar']",
],
```

**Expected:**
```json
"type": "rule",
"selectors": [
    "div[data-value='foo']",
    "div[data-value='bar']"
],
```

I have attached a test case demonstrating this. You can extract the archive directly into `test/cases/`:
[case - selectors-attributes.zip](https://github.com/adobe/css-tools/files/10156598/case.-.selectors-attributes.zip)

**Comment by holblin** [comment]
Thanks a lot for the report, I will work on it as soon as I get some time.

**Comment by holblin** [comment]
Hi @RandomByte , could you check if this PR fixes your problems?
- https://github.com/adobe/css-tools/pull/88
I plan to merge it within a week if I found no issues with it.

**Comment by matz3** [comment]
@holblin thanks! I can confirm that it resolves all issues we were facing.

**Comment by holblin** [comment]
The new version is published in npm 👍 
Thanks for the report! It was much appreciated :-)
