### ISSUE TITLE
@layer support needs to be added

### ISSUE THREAD

**Issue by jogibear9988** [adobe/css-tools#91]
### Expected Behaviour
@layer rules should be parsed

### Actual Behaviour
they are not parsed, see also: https://github.com/reworkcss/css/issues/165

### Reproduce Scenario (including but not limited to)
    
    var css = require('css');
    var obj = css.parse("@layer mylayer {.card {--content-box-flex-grow: 1; display: flex; flex-direction: column; position: relative; width: 100%;} }");
    css.stringify(obj);

**Comment by jogibear9988** [comment]
I can look to work on this

**Comment by jogibear9988** [comment]
fixed in #97

**Comment by holblin** [comment]
Thanks a lot for your contribution! Sorry I wasn't able to review and merge earlier. A new version should be available soon on npmjs 👍
