### ISSUE TITLE
@container support needs to be added

### ISSUE THREAD

**Issue by jogibear9988** [adobe/css-tools#92]
### Expected Behaviour
@container rules should be parsed

### Actual Behaviour
they are not parsed

### Reproduce Scenario (including but not limited to)

    @container (min-width: 700px) {
      .card h2 {
        font-size: 2em;
      }
    }

**Comment by holblin** [comment]
Thanks a lot for your contribution! Sorry I wasn't able to review and merge earlier. A new version should be available soon on npmjs 👍
